-- Perilumio ABU QV Seed
insert into modules (id, title, description) values
('abu-qv', 'Allgemeinbildung QV', 'QV-naher ABU-Kurs für Sprache, Gesellschaft und Alltag.')
on conflict (id) do update set title=excluded.title, description=excluded.description;

insert into lessons (id, module_id, title, position, pass_score) values
('abu-1','abu-qv','Textverständnis und Kernaussagen',1,70),
('abu-2','abu-qv','Argumentieren und Stellung nehmen',2,70),
('abu-3','abu-qv','Berufliche Kommunikation',3,70),
('abu-4','abu-qv','Lehrvertrag und Arbeitsrecht',4,70),
('abu-5','abu-qv','Verträge im Alltag',5,70),
('abu-6','abu-qv','Lohn, Budget und Fixkosten',6,70),
('abu-7','abu-qv','Versicherungen und Vorsorge',7,70),
('abu-8','abu-qv','Demokratie und Staat Schweiz',8,70),
('abu-9','abu-qv','Medien und Meinungsbildung',9,70),
('abu-10','abu-qv','Konsum, Schulden und Verantwortung',10,70)
on conflict (id) do update set module_id=excluded.module_id, title=excluded.title, position=excluded.position, pass_score=excluded.pass_score;

-- Questions import via CSV using supabase/seeds/abu_qv_questions.csv

create table if not exists import_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  row_count integer default 0,
  created_at timestamptz default now()
);
